### PR TITLE
solves distogram median and int2char

### PR DESCRIPTION
**Pull request by hypnopump**
.

### CODE REVIEW

**Comment by lucidrains** [comment]
@hypnopump it breaks if i do that :laughing:

**Comment by lucidrains** [comment]
@hypnopump adding tests in another PR :)

**Comment by lucidrains** [comment]
@hypnopump I made an attempt to fix it in the latest commit, but could use a second look

**Comment by hypnopump** [comment]
* solves int2char issue (workaround to load from sidechainnet)
* solves cuda median issue (and aditional shape inconsistencies) + nans in weights + minor things

**Pull request merged**
