### PR TITLE
clean more masked_fills

### PR DESCRIPTION
**Pull request by hypnopump**
* simplify diag masking to 0 in center_distogram
* clean masked_fill_ in mds_torch

### CODE REVIEW

**Comment by lucidrains** [comment]
Ohh, I was worried that one of these operations was causing the inplace error on backwards

Was it resolved by your previous commit? You can test by just doing coords.sum().backwards() many times

**Comment by lucidrains** [comment]
Basically, run this script like 10 times, and if it can pass all of them, we are good

```python
import torch
from alphafold2_pytorch import Alphafold2

model = Alphafold2(
    dim = 256,
    depth = 2,
    heads = 8,
    dim_head = 64,
    predict_coords = True,
    structure_module_dim = 4,               # se3 transformer dimension
    structure_module_depth = 1,             # depth
    structure_module_heads = 1,             # heads
    structure_module_dim_head = 16,         # dimension of heads
    structure_module_refinement_iters = 2   # number of equivariant coordinate refinement iterations
).cuda()

seq = torch.randint(0, 21, (2, 64)).cuda()
msa = torch.randint(0, 21, (2, 5, 32)).cuda()
mask = torch.ones_like(seq).bool().cuda()
msa_mask = torch.ones_like(msa).bool().cuda()

coords = model(
    seq,
    msa,
    mask = mask,
    msa_mask = msa_mask
) # (2, 64, 3)

coords.sum().backward()
```

**Comment by hypnopump** [comment]
Solved. At least in cpu. The error was in overwriting dist_mat. Added `.clone()` to the output of `torch.cdist()`.

I'm sorry for the masked_fills. Collateral damage

**Comment by lucidrains** [comment]
@hypnopump amazing! 🙏 🔥

**Comment by lucidrains** [comment]
@hypnopump ohh, I think there's still some remaining bug. I am seeing a NaN error now `RuntimeError: Function 'DivBackward0' returned nan values in its 1th output.`

**Comment by lucidrains** [comment]
@hypnopump try running

```python
import torch
from alphafold2_pytorch import Alphafold2
torch.autograd.set_detect_anomaly(True)
model = Alphafold2(
    dim = 256,
    depth = 2,
    heads = 8,
    dim_head = 64,
    predict_coords = True,
    structure_module_dim = 4,               # se3 transformer dimension
    structure_module_depth = 1,             # depth
    structure_module_heads = 1,             # heads
    structure_module_dim_head = 16,         # dimension of heads
    structure_module_refinement_iters = 2   # number of equivariant coordinate refinement iterations
).cuda()

seq = torch.randint(0, 21, (2, 64)).cuda()
msa = torch.randint(0, 21, (2, 5, 32)).cuda()
mask = torch.ones_like(seq).bool().cuda()
msa_mask = torch.ones_like(msa).bool().cuda()

coords = model(
    seq,
    msa,
    mask = mask,
    msa_mask = msa_mask
) # (2, 64, 3)

coords.sum().backward()
```

on a colab with GPU

**Comment by hypnopump** [comment]
Done: https://colab.research.google.com/drive/1RHvKHY1vVFeQaeRCrFfAWXLGrx-ACuEj?usp=sharing

Pretty sure the MDS / center_distogram works though, tested it below so you can double check it.

**Comment by lucidrains** [comment]
@hypnopump aghh still seeing errors :cry:  I've committed in the broken test, so maybe it'll be easier for you to test it on a branch until it passes

**Comment by hypnopump** [comment]
i think the error must be somewhere in the se3 or the combination of se3 + mds. I have produced the computational graphs for both the error in AF2 and the clean pass through center_histogram and MDS (they're in the colab notebook i linked above)

[lolasso_af2.pdf](https://github.com/lucidrains/alphafold2/files/6084578/lolasso_af2.pdf)
[lolasso_works.pdf](https://github.com/lucidrains/alphafold2/files/6084579/lolasso_works.pdf)

**Pull request merged**
