### PR TITLE
Solved various things [list]

### PR DESCRIPTION
**Pull request by hypnopump**
* solved dihedrals
* solved shape issues
* should fix the CUDA - median thing
* wrote some docs

TODO:
- [x] Fix the wrappers. they don't work (torch/numpy ...)

### CODE REVIEW

**Comment by lucidrains** [comment]
@hypnopump oops, fixed the utils wrapper for torch / numpy, i'll add some more tests later in the evening

**Comment by hypnopump** [comment]
Should work. The sidechain should be predicted by the se3. the utils create a wrapper for the coords and a fast variant of nerf is provided to (optional) place the oxygen in the carbonyl group.

**Comment by lucidrains** [comment]
@hypnopump looks good! do you want to try adding a test under the `tests/` directory?

**Comment by hypnopump** [comment]
Finally, All tests pass! Parallelizes dihedral angle calculations and the natural extension of reference frame.

**Comment by lucidrains** [comment]
🥇

**Pull request merged**
