### PR TITLE
gets rid of mirrors for mds -> faster and can do batched folding

### PR DESCRIPTION
**Pull request by hypnopump**
* Fixed an angle issue in the `nerf_torch` function
* Now it calculates the error with the aligned structures.

### CODE REVIEW

**Comment by lucidrains** [comment]
@hypnopump looks good, save for a failing test :)

**Comment by hypnopump** [comment]
yea it's because the test hasn't been updated, but the modification is correct. it was discussed here: https://github.com/jonathanking/sidechainnet/issues/14

i'll fix the test tomorrow.

**Comment by hypnopump** [comment]
- Fixed MDS numpy
- got rid of mirrors (now faster ~3x faster) in favour of a simple multiplication that does the job and allows for batched mds (as long as distograms provided are the same shape)
- solved issues in tests

**Comment by lucidrains** [comment]
⭐ 🚀

**Pull request merged**
