### PR TITLE
Add attn embedding

### PR DESCRIPTION
**Pull request by hypnopump**

### CODE REVIEW

**Comment by lucidrains** [comment]
nice! i think, realistically though, no one is going to ever use the 'cpu' version for training

**Comment by hypnopump** [comment]
yea me neither but https://github.com/lucidrains/alphafold2/issues/17#issuecomment-764598239 this guy asked for it

**Comment by hypnopump** [comment]
Implemented ESM embeddings (check the msa replacement in `alphafold2.py` to see inner workings) and adapted `train_end2end.py` for it:
```python3
elif exists(embedds):
    m = self.embedd_project(embedds)
    # pairwise mat - maybe repeating stuff? 
    m = m[:, :, None, :] + m[:, None, :, :]
    m = rearrange(m, 'b m n d -> b (m n) d')
```

Follow the same process as in the readme and https://colab.research.google.com/github/facebookresearch/esm/blob/master/examples/variant_prediction.ipynb (from the esm repo) to encode sequences.

This should allow for training just with sequences.

**Review by lucidrains — APPROVED** [review]
💯

**Pull request merged**
